/**
 * Document model — the typed block stream that replaces "PDF → one big string".
 *
 * Everything downstream (chunking, fault extraction, retrieval, citations) reads
 * these types and nothing else, so the parsing backend (LlamaParse today, a
 * different vendor or a self-hosted parser tomorrow) is swappable without
 * touching the pipeline.
 *
 * Written in erasable-only TypeScript so it runs under `node --experimental-strip-types`
 * with no build step.
 */

// ---------------------------------------------------------------------------
// Blocks
// ---------------------------------------------------------------------------

/** What a block *is*. Drives chunking atomicity and retrieval weighting. */
export type BlockKind =
  | "heading"
  | "para"
  | "table"
  | "steps"
  | "admonition"
  | "figure"
  | "caption"
  | "list";

/** Where the text came from. Propagates into chunks so refusal logic can distrust OCR. */
export type TextSource = "digital" | "ocr" | "vlm";

export type AdmonitionSeverity = "danger" | "warning" | "caution" | "notice";

/** A table preserved as structure, not as flattened prose. */
export interface TableData {
  /** Column headers, normalized (trimmed, collapsed whitespace). Empty if headerless. */
  header: string[];
  /** Body rows. Every row is padded/truncated to header.length once normalized. */
  rows: string[][];
  /** Markdown rendering — what actually gets embedded and shown to the LLM. */
  markdown: string;
  /** Set when a table continues across a page break and we stitched it. */
  spansPages?: number[];
}

export interface FigureData {
  figureId: string;
  /** "Figure 7-3" etc., when a caption was found. */
  label?: string;
  caption?: string;
  /** Storage URL/path. Never inline base64 — that bloated the old Qdrant payloads. */
  href?: string;
}

export interface StepData {
  n: number;
  text: string;
  /** Warnings bound to this specific step; never separated from it. */
  warnings?: string[];
}

/**
 * One structural unit of a document.
 *
 * `sectionPath` is the breadcrumb from the PDF outline (exact) or from heading
 * detection (fallback), e.g. ["Fault tracing", "Fault messages generated by the drive"].
 */
export interface Block {
  id: string;
  documentId: string;
  kind: BlockKind;

  /** Plain-text rendering of the block. For tables this is the markdown. */
  text: string;

  /** 1-based index into the PDF's physical pages. */
  pagePdf: number;
  /** The number *printed on the page* ("5-12", "130"). What a citation must show. */
  pageLabel: string;

  sectionPath: string[];
  /** Heading depth for kind === "heading"; the enclosing depth otherwise. */
  level: number;

  textSource: TextSource;
  ocrConfidence?: number;

  table?: TableData;
  figure?: FigureData;
  steps?: StepData[];
  admonition?: { severity: AdmonitionSeverity; text: string };

  /** Measurements found in the block, for keyword/filter search ("45 Nm", "135 °C"). */
  units?: string[];
}

// ---------------------------------------------------------------------------
// Document
// ---------------------------------------------------------------------------

export interface OutlineEntry {
  title: string;
  /** 1-based physical page the bookmark points at. */
  pagePdf: number;
  level: number;
}

export interface DocumentMeta {
  documentId: string;
  title: string;
  /** Stable slug used for filtering in the vector DB: "abb-acs150". */
  machineId: string;
  /** Human label: "ACS150". */
  model?: string;
  manufacturer?: string;
  docType?: "user_manual" | "programming_manual" | "product_manual" | "service_manual" | "other";
  revision?: string;
  language?: string;
  pageCount: number;
  /** sha256 of the source file — the cache key for parse/embed reuse. */
  sha256: string;
}

export interface ParsedDocument {
  meta: DocumentMeta;
  blocks: Block[];
  outline: OutlineEntry[];
}

// ---------------------------------------------------------------------------
// Fault records — the highest-value structure in the whole system
// ---------------------------------------------------------------------------

/**
 * Error Code → Meaning → Cause → Corrective Action, extracted once at ingest.
 *
 * When a query names a code, we return this record instead of asking the LLM to
 * re-derive the structure from prose. The LLM's job drops to phrasing, which is
 * where most hallucination risk disappears.
 */
export interface FaultRecord {
  faultId: string;
  /** As printed: "F0001", "E101", "OCF". */
  codeRaw: string;
  /** Casefolded, separators stripped, for exact lookup: "f0001". */
  codeNorm: string;

  machineId: string;
  model?: string;

  /** The short name: "OVERCURRENT". */
  meaning: string;
  causes: string[];
  steps: StepData[];
  severity?: AdmonitionSeverity;

  provenance: Provenance;
  extraction: "table_row" | "section";
  /** 0..1 — how much of the record the extractor actually filled in. */
  confidence: number;
}

// ---------------------------------------------------------------------------
// Chunks + provenance
// ---------------------------------------------------------------------------

/** The citation chain: answer → chunk → section → page → manual. */
export interface Provenance {
  documentId: string;
  title: string;
  sectionPath: string[];
  pagePdf: number;
  pageLabel: string;
  blockIds: string[];
}

export interface Chunk {
  id: string;
  documentId: string;
  title: string;

  /** Breadcrumb-prefixed text — what gets embedded. */
  text: string;
  charCount: number;

  machineId: string;
  model?: string;

  sectionPath: string[];
  pagePdf: number;
  pageLabel: string;

  blockKinds: BlockKind[];
  /** True when the chunk is a single indivisible unit (table, step list, warning). */
  atomic: boolean;
  partIndex?: number;
  partTotal?: number;

  /** Codes mentioned anywhere in the chunk — feeds the exact-match code index. */
  faultCodes: string[];
  units: string[];
  figureRefs: string[];
  textSource: TextSource;

  blockIds: string[];
}

// ---------------------------------------------------------------------------
// Helpers shared across the ingest modules
// ---------------------------------------------------------------------------

/** Normalize a fault code for exact matching: "F 0001" / "f-0001" → "f0001". */
export function normalizeCode(raw: string): string {
  return raw.toLowerCase().replace(/[\s._-]/g, "");
}

/**
 * Alternatives are ordered longest-first (mm before m, kV before V) because the
 * regex engine takes the first match, not the longest. The trailing lookahead
 * replaces `\b` so that "%" — not a word character — still terminates a match.
 */
const UNIT_RE =
  /\b(\d+(?:[.,]\d+)?)\s?(mm|cm|kPa|MPa|psi|bar|°C|°F|degC|degF|kHz|Hz|kV|mA|kW|Nm|lb-?ft|rpm|in|ft|m|V|A|W|%)(?![A-Za-z])/gi;

/** Extract measurements for keyword search. Non-destructive: originals stay in the text. */
export function extractUnits(text: string): string[] {
  const out = new Set<string>();
  for (const m of text.matchAll(UNIT_RE)) out.add(`${m[1]} ${m[2]}`);
  return [...out];
}

/**
 * Fault-code shapes seen across ABB and Schneider manuals:
 *   ABB drives      F0001, A2001, 0005
 *   ABB robot       50204
 *   Schneider ATV   OCF, SOF, InF, USF   (3-4 letter mnemonics)
 *   generic         E101, b005, F012
 *
 * Deliberately conservative — a looser pattern turns ordinary words into codes,
 * which is what broke exact-match retrieval in the original implementation.
 */
const CODE_RES = [
  /\b([A-Z]{1,3}\d{3,5})\b/g, // F0001, E101, A2001
  /\b([A-Z]{2,4}F)\b/g, // OCF, SOF, InF, USF — Schneider "…F" fault mnemonics
];

export function extractFaultCodes(text: string): string[] {
  const out = new Set<string>();
  for (const re of CODE_RES) {
    for (const m of text.matchAll(re)) out.add(m[1]);
  }
  return [...out];
}

/** Render a breadcrumb prefix. Costs nothing, measurably improves dense + lexical recall. */
export function breadcrumb(machineLabel: string, sectionPath: string[]): string {
  return [machineLabel, ...sectionPath].filter(Boolean).join(" › ");
}
