"""Generate dense, realistic factory manuals with rich technical content.

Each manual is 3-5 pages of dense technical prose, tables, error codes, and
procedural steps. Designed to test cross-document disambiguation, structured
retrieval, and hallucination control.
"""
from __future__ import annotations

from pathlib import Path

import pymupdf

OUT = Path(__file__).resolve().parent.parent / "manuals"
OUT.mkdir(parents=True, exist_ok=True)


def build_pdf(filename: str, title: str, pages: list[str]) -> Path:
    path = OUT / filename
    doc = pymupdf.open()
    for i, body in enumerate(pages, start=1):
        page = doc.new_page()
        header = f"{title}  —  Page {i}"
        page.insert_textbox((50, 40, 545, 60), header, fontsize=11, fontname="helv")
        page.insert_textbox((50, 80, 545, 780), body, fontsize=9, fontname="helv")
    doc.save(path)
    doc.close()
    size_kb = path.stat().st_size // 1024
    print(f"  {path.name}  ({size_kb} KB, {len(pages)} pages)")
    return path


def roboinject() -> None:
    build_pdf(
        "RoboInject-300-Manual.pdf",
        "RoboInject-300 Service Manual",
        [
            # Page 1
            "1. INTRODUCTION\n\n"
            "The RoboInject-300 is a fully electric injection molding machine (serial prefix SM-) "
            "manufactured by RoboMech Industries. It features a servo-driven injection arm with "
            "a peak clamping force of 300 tons and four independent barrel heating zones. "
            "This service manual covers all units with control system version 4.3 and above.\n\n"
            "1.1 SAFETY SYMBOLS\n"
            "WARNING — Risk of electrical shock or personal injury. Failure to follow "
            "instructions may result in death or severe injury.\n"
            "CAUTION — Risk of damage to equipment or minor injury.\n"
            "NOTE — Additional information to aid in operation.\n\n"
            "1.2 TECHNICAL SPECIFICATIONS\n"
            "Power supply: 480V 3-phase, 60A\n"
            "Servo motor rating: 15 kW continuous, 22 kW peak\n"
            "Barrel zones: 4 × 1500W heater bands\n"
            "Max barrel temperature: 350°C\n"
            "Cooling: forced air via 230V AC fan (0.25 kW)\n"
            "Controller: RoboMech RM-430 with 7-inch HMI\n"
            "Weight: 4,200 kg\n\n"
            "1.3 LUBRICATION SYSTEM\n"
            "The central lubrication system uses ISO-VG-68 grease. The reservoir holds 1.5 L "
            "and the pump delivers 0.5 mL per cycle to the ball screw and linear guides. "
            "Low oil level triggers alarm A107 on the HMI display. Refill port is located "
            "behind the front access panel, secured with two M6 hex bolts.\n\n"
            "1.4 MAINTENANCE SCHEDULE\n"
            "Daily: inspect cooling fan intake for debris, check oil level, verify no "
            "alarm codes on the HMI.\n"
            "Weekly: clean air filter, verify zone temperatures within ±5°C of setpoint, "
            "check servo drive cooling fan operation.\n"
            "Monthly: inspect injection arm ball screw for wear, check belt tension, "
            "perform sensor calibration per §6.0.\n"
            "Quarterly: replace air filter, inspect all electrical connections, test "
            "safety interlocks per §7.3.\n"
            "Annually: full calibration, replace heating bands if resistance deviates "
            "more than 10% from nominal, replace lubrication pump filter.",

            # Page 2
            "4. ERROR CODE REFERENCE\n\n"
            "4.1 E101 — Winding Overtemperature\n"
            "Meaning: The temperature of the injection servo motor windings has exceeded "
            "the safe operating threshold of 130°C. The controller automatically reduces "
            "current to prevent thermal damage to the winding insulation. If the temperature "
            "reaches 150°C, the drive will trip and a hard fault is logged.\n\n"
            "Probable causes (in order of frequency):\n"
            "1. Blocked cooling fan intake — most common cause. Debris accumulates on the "
            "fan grille located at the rear of the servo drive enclosure.\n"
            "2. Dirty or clogged air filter — the foam air filter element should be "
            "replaced quarterly (P/N AF-300-12).\n"
            "3. Failed NTC temperature sensor — the winding thermistor may drift out of "
            "specification, causing false high readings.\n"
            "4. Excessive duty cycle — running the machine at full cycle rate for more "
            "than 4 hours without a cooldown period can cause thermal buildup.\n\n"
            "Corrective action:\n"
            "Step 1. Power down the machine and lock out the main disconnect per §1.1.\n"
            "Step 2. Inspect the cooling fan on the rear of the servo drive enclosure. "
            "Remove any debris, lint, or dust accumulation from the intake grille.\n"
            "Step 3. Replace the air filter if visibly dirty (P/N AF-300-12). The filter "
            "is located behind the hinged cover on the right side of the cabinet.\n"
            "Step 4. Measure the NTC sensor resistance between pins 3 and 4 on the sensor "
            "harness connector (J3 on the drive PCB). Expected value at 25°C: 2.4 kΩ ±5%. "
            "At 50°C: 1.1 kΩ ±8%. At 100°C: 0.28 kΩ ±10%. If readings deviate by more "
            "than 8% from nominal, replace the sensor assembly (P/N NTC-R300).\n"
            "Step 5. If the sensor checks out, verify 24V DC supply to the fan motor at "
            "terminal block TB2, pins 1 (+24V) and 2 (common). Voltage should be 24V DC ±10%.\n"
            "Step 6. Restart the machine and run under load for 20 minutes. Monitor the "
            "winding temperature on the HMI (Diagnostics > Drive Status > Winding Temp). "
            "Temperature should stabilize below 110°C.\n\n"
            "Source: Section 4.2, page 214. Referenced in SS-300 Quick Reference guide §E.\n\n"
            "4.2 E204 — Servo Stall Detected\n"
            "Meaning: The injection arm servo motor has exceeded its torque limit and the "
            "controller has triggered a stall protection routine. The arm may be mechanically "
            "bound, or the servo drive parameters may be incorrect for the current mold.\n\n"
            "Probable causes:\n"
            "1. Mechanical obstruction in the injection arm rails — check for foreign objects, "
            "burrs, or contamination on the linear rail surfaces.\n"
            "2. Worn or damaged ball screw — excessive backlash or visible pitting on the "
            "screw threads indicates the ball screw requires replacement.\n"
            "3. Servo drive current limit set too low — parameter P-07 (peak current limit) "
            "should be set to 12A for standard molds. Increase to 14A for heavy molds.\n"
            "4. Incorrect acceleration ramp — parameter P-12 (acceleration time) should not "
            "be set below 500 ms for the injection arm.\n\n"
            "Corrective action:\n"
            "Step 1. Clear the fault on the HMI (Main Menu > Faults > Reset Fault).\n"
            "Step 2. Manually jog the injection arm to full retract and full extend using "
            "the manual mode on the HMI. Listen for grinding, binding, or unusual noises.\n"
            "Step 3. Inspect the ball screw for visible wear, pitting, or contamination. "
            "Measure backlash at the center of travel: maximum acceptable is 0.15 mm.\n"
            "Step 4. Check servo drive parameter P-07. If below 12A, increase to 12A. "
            "For molds heavier than 50 kg, increase to 14A.\n"
            "Step 5. Verify acceleration ramp P-12 is ≥ 500 ms. Lower values cause "
            "excessive peak torque demand.\n"
            "Source: Section 8.3, page 312.\n\n"
            "4.3 E302 — Zone 1 Heater Overcurrent\n"
            "Meaning: The electrical current draw on barrel zone 1 exceeds 20A. This "
            "indicates a shorted heating band or damaged wiring insulation.\n\n"
            "Corrective action:\n"
            "Step 1. Switch off zone 1 from the controller.\n"
            "Step 2. Measure resistance across the heating band terminals. The expected "
            "value is 11.5 Ω ±1 Ω at 20°C. If the reading is near 0 Ω, the band is shorted.\n"
            "Step 3. Replace the heating band (P/N HB-1-300). Torque the retaining bolts "
            "to 12 N·m.\n\n"
            "Source: Section 9.1, page 378.",

            # Page 3
            "6. SENSOR CALIBRATION PROCEDURES\n\n"
            "6.1 NTC Winding Temperature Sensor\n"
            "The winding temperature sensor is a negative-temperature-coefficient (NTC) "
            "thermistor. Calibration should be performed annually or whenever the sensor "
            "is replaced. Use the following reference table:\n\n"
            "Temperature     Resistance (nominal)    Tolerance\n"
            "25°C            2.40 kΩ                 ±5%\n"
            "50°C            1.10 kΩ                 ±8%\n"
            "75°C            0.55 kΩ                 ±8%\n"
            "100°C           0.28 kΩ                 ±10%\n"
            "120°C           0.18 kΩ                 ±10%\n\n"
            "To calibrate: immerse the sensor tip in a calibrated oil bath at the "
            "reference temperature and compare the measured resistance. If the reading "
            "deviates by more than the tolerance, replace the sensor (P/N NTC-R300). "
            "Ensure the sensor tip is fully inserted into the thermal well and coated "
            "with heat-conductive paste (P/N TCP-100).\n\n"
            "6.2 Type-K Thermocouple Calibration (Barrel Zones)\n"
            "Each barrel zone uses a Type-K thermocouple with a measurement range of "
            "0-400°C. Cold junction compensation is handled automatically by the "
            "controller board. If zone temperature readings are erratic or deviate by "
            "more than ±10°C from setpoint:\n"
            "Step 1. Swap the suspect thermocouple with an adjacent zone to isolate "
            "whether the fault follows the sensor or the controller channel.\n"
            "Step 2. If the fault follows the sensor, replace the thermocouple (P/N TC-K-300).\n"
            "Step 3. If the fault stays on the same channel, the controller input board "
            "may need replacement.\n\n"
            "6.3 Pressure Transducer Calibration\n"
            "The injection pressure transducer (range 0-250 bar, output 4-20 mA) should "
            "be zeroed annually. With the system at atmospheric pressure, adjust the "
            "'Zero' potentiometer on the transducer signal conditioner to read 4.00 mA "
            "at the controller input. The full-scale reading should be 20.00 mA at 250 bar.",

            # Page 4
            "7. ELECTRICAL SYSTEM\n\n"
            "7.1 MAIN FUSE RATINGS\n"
            "Main AC input (L1, L2, L3): 3 × 32A class gG, P/N F-M300-MAIN\n"
            "Servo drive input: 2 × 16A class aM, P/N F-M300-SERVO\n"
            "Control circuit transformer primary: 1 × 6.3A class gG, P/N F-M300-CTRL\n"
            "Heater zone contactors: 1 × 25A per zone class gG\n"
            "24V DC power supply: 1 × 4A class gG\n\n"
            "WARNING: Always disconnect and verify zero energy state before accessing "
            "the fuse panel. The DC bus capacitors can retain lethal charge for up to "
            "5 minutes after power-down.\n\n"
            "7.2 CONTROL BOARD STATUS LEDS\n"
            "D1 (green, steady) — 24V DC control power present\n"
            "D2 (yellow, flashing) — CAN bus communication active\n"
            "D3 (red, steady) — Fault latch active (see error code on HMI)\n"
            "D4 (amber, flashing) — Maintenance reminder (service interval due)\n\n"
            "7.3 SAFETY INTERLOCK CIRCUIT\n"
            "All access doors are monitored by magnetic safety switches (MSS-300, 2NC "
            "contacts each). The interlock circuit is dual-channel, monitored by the "
            "safety PLC. Both channels must close within 500 ms of each other for the "
            "machine to start. If the controller shows 'E011 — Safety Loop Open' on the "
            "HMI diagnostics screen:\n"
            "Step 1. Open and close each access door one at a time while watching the "
            "I/O status on the HMI (Diagnostics > I/O Map > Safety Inputs).\n"
            "Step 2. Identify the door switch that does not toggle.\n"
            "Step 3. Replace the faulty switch (P/N MSS-300). Torque the mounting "
            "screws to 3 N·m. Align the actuator with the center of the switch body.\n\n"
            "7.4 WIRING DIAGRAM REFERENCE\n"
            "Full wiring diagrams are provided in Appendix A, sheets A-1 through A-12. "
            "Key connections:\n"
            "TB1-1,2: 480V AC main input\n"
            "TB2-1,2: 24V DC fan supply\n"
            "TB3-1 through 4: heater zone outputs\n"
            "J3-1 through 4: NTC sensor input\n"
            "J5-1 through 8: safety interlock inputs",
        ],
    )


def press2000() -> None:
    build_pdf(
        "Press-2000-Manual.pdf",
        "Press-2000 Hydraulic Press Manual",
        [
            # Page 1
            "1. MACHINE OVERVIEW\n\n"
            "The Press-2000 is a 2000-ton hydraulic shop press (serial prefixes HY- and HP-) "
            "manufactured by HydraForm Industries. It uses a dual-pump hydraulic system "
            "rated for ISO-VG68 hydraulic fluid at 210 bar maximum operating pressure. "
            "The press is designed for stamping, forming, and deep-drawing operations on "
            "metal sheets up to 6 mm thickness.\n\n"
            "WARNING: The Press-2000 hydraulic system stores significant energy even when "
            "the pump motor is off. The accumulator can maintain pressure for up to 30 "
            "minutes after shutdown. Always follow the pressure bleed procedure in §12.4 "
            "before opening any hydraulic line or fitting.\n\n"
            "IMPORTANT: The Press-2000 uses a different error code scheme from the "
            "RoboInject line of machines. Error codes E101 and E204 on the Press-2000 "
            "have DIFFERENT meanings than on the RoboInject-300. Always confirm the "
            "machine model before applying any corrective action. Section 3 of this "
            "manual provides a complete cross-reference of all error codes.\n\n"
            "1.1 DAILY OPERATOR CHECKS\n"
            "- Visually inspect hydraulic fluid level in the reservoir sight glass. "
            "Fluid must be between the MIN and MAX marks.\n"
            "- Check the pressure gauge reading at idle (should read 0-5 bar).\n"
            "- Verify all safety light curtains are clean and free of obstructions.\n"
            "- Listen for abnormal pump cavitation sounds during the warm-up cycle.\n"
            "- Verify that the ram returns fully to the top-of-stroke position.\n\n"
            "1.2 TECHNICAL SPECIFICATIONS\n"
            "Maximum pressing force: 2000 tons (19,600 kN)\n"
            "Main pump: Vickers vane pump, 120 L/min at 1450 RPM\n"
            "Pilot pump: gear pump, 8 L/min for control circuits\n"
            "Reservoir capacity: 180 L of ISO-VG68 hydraulic fluid\n"
            "Main motor: 75 kW, 480V 3-phase, 1450 RPM\n"
            "Controller: HydraForm HC-5000 with 10-inch touchscreen",
            # Page 2
            "3. ERROR CODE REFERENCE\n\n"
            "3.1 E101 — Low Hydraulic Pressure\n\n"
            "CRITICAL: This code means LOW HYDRAULIC PRESSURE on the Press-2000. "
            "It is NOT the same as E101 on the RoboInject-300 (winding overtemperature) "
            "or the Press-2001 (drive chain binding). Applying the wrong machine's "
            "corrective action may cause further damage and create safety hazards.\n\n"
            "Meaning: The main hydraulic system pressure has fallen below 150 bar during "
            "the press stroke. The press controller will stop the stroke immediately and "
            "hold the ram at its current position. The alarm horn will sound continuously "
            "until the fault is acknowledged on the HMI.\n\n"
            "Probable causes (in order of frequency):\n"
            "1. Hydraulic fluid level below the minimum mark in the reservoir — the most "
            "common and easily correctable cause.\n"
            "2. Worn main pump seal allowing internal leakage — the vane pump's internal "
            "seal wears over time, reducing volumetric efficiency.\n"
            "3. Relief valve stuck partially open or set below the 210 bar specification.\n"
            "4. External leak in the main pressure line between the pump and the manifold "
            "block — check all threaded unions and flanged connections.\n"
            "5. Air ingress into the hydraulic system — aerated fluid appears milky or "
            "foamy in the reservoir sight glass.\n\n"
            "Corrective action:\n"
            "Step 1. Check the reservoir sight glass. Fluid must be between the MIN and "
            "MAX marks. Top up with ISO-VG68 hydraulic fluid if needed. Total system "
            "capacity is 180 L, including the lines and cylinders.\n"
            "Step 2. Inspect the main pump seal. The pump is located behind the cover "
            "on the motor bell housing (four M8 bolts). Oil drip from the weep hole "
            "indicates a failed shaft seal. Replace using seal kit P/N PS-2000-SEAL.\n"
            "Step 3. Test the relief valve setting. In manual mode, slowly increase "
            "pressure while watching the pressure gauge. The relief valve should crack "
            "open at 210 bar ±5 bar. Adjust using the hex nut on the valve body "
            "(clockwise to increase cracking pressure). Do not exceed 225 bar.\n"
            "Step 4. Check all threaded unions on the main pressure line. Tighten any "
            "loose fittings. Look for wet spots, drips, or oil mist indicating a leak.\n"
            "Step 5. Bleed air from the system: open the bleed valve at the top of the "
            "manifold block. Run the pump for 30 seconds. Close the valve when a steady "
            "stream of oil without bubbles appears.\n\n"
            "Source: Section 3.1, page 92.",
            # Page 3
            "3.2 E204 — High Pressure Exceeded\n\n"
            "Meaning: The hydraulic pressure has exceeded 225 bar (the overpressure "
            "limit). The press has triggered an emergency stop and the main pump "
            "contactor has dropped out.\n\n"
            "Probable causes:\n"
            "1. Intensifier valve stuck in the closed position — the pressure intensifier "
            "should automatically divert flow when the set pressure is reached.\n"
            "2. Pressure transducer sensor fault — the transducer sends a 4-20 mA signal "
            "to the controller. A failed sensor may report 4 mA continuously, causing "
            "the controller to never detect the set pressure.\n"
            "3. Control board pressure limit parameter incorrectly set above 210 bar.\n\n"
            "Corrective action:\n"
            "Step 1. Reset the emergency stop by pulling the E-stop button on the "
            "operator panel. Clear the fault code on the HMI (Main Menu > Faults).\n"
            "Step 2. Test the pressure transducer. Remove the transducer from the manifold "
            "and connect a digital multimeter to pins 1 (+24V) and 3 (signal). At "
            "atmospheric pressure, the signal should read 4.00 mA ±0.1 mA. Apply known "
            "pressure using a hand pump; the signal should increase linearly to 20.00 mA "
            "at 250 bar. Replace if outside tolerance.\n"
            "Step 3. In the controller menu, navigate to Settings > Pressure Limits. "
            "Verify PR-LIMIT is set to 210 bar. If not, adjust and save.\n\n"
            "Source: Section 5.2, page 138.\n\n"
            "4. HYDRAULIC SYSTEM MAINTENANCE\n\n"
            "4.1 Pump Service Intervals\n"
            "The main vane pump (P/N VP-2000) should be serviced every 2000 operating "
            "hours with the following kit:\n"
            "- Vane cartridge replacement kit (P/N VC-2000-KIT). Includes vanes, rotor, "
            "and cam ring.\n"
            "- Inlet strainer (P/N IF-2000) — clean or replace.\n"
            "- Return line filter element (P/N RF-2000).\n"
            "- Inspect the pump-to-motor coupling for wear or rubber deterioration.\n\n"
            "4.2 Hydraulic Fluid Specification\n"
            "Use only ISO-VG68 anti-wear hydraulic fluid. Do not mix with other grades "
            "or viscosities. The system holds approximately 180 L. Fluid temperature "
            "during normal operation should be 40-55°C. If temperature exceeds 65°C, "
            "check the oil cooler for blocked fins and clean with compressed air.\n\n"
            "4.3 Pressure Test Procedure\n"
            "Connect the digital pressure tester to test port TP-1 on the manifold. "
            "Run the press through one complete cycle in manual mode. Record the peak "
            "pressure — it should reach 210 bar ±5 bar. If peak pressure is below 190 "
            "bar, suspect pump wear or a relief valve set too low.",
        ],
    )


def press2001() -> None:
    build_pdf(
        "Press-2001-Manual.pdf",
        "Press-2001 Mechanical Press Manual",
        [
            "1. MACHINE IDENTIFICATION\n\n"
            "The Press-2001 is a 1500-ton mechanical (flywheel) press with serial prefix "
            "MP-. Unlike the Press-2000, this machine has NO hydraulic system. Clamping "
            "force is generated by a motor-driven flywheel and eccentric gear mechanism. "
            "Do NOT apply Press-2000 hydraulic error codes or corrective actions to this "
            "machine. The Press-2001 uses a pneumatically actuated clutch and brake unit "
            "with a spring-applied, air-released brake design.\n\n"
            "1.1 LUBRICATION SYSTEM\n"
            "The main gearbox and clutch assembly are splash-lubricated with ISO-VG220 "
            "gear oil. The reservoir holds 6 L. Change the oil every 3000 operating hours "
            "or 12 months, whichever comes first. The slide guides are grease-lubricated "
            "via grease fittings on the front and rear of each guide rail. Apply "
            "lithium-based NLGI 2 grease weekly.\n\n"
            "1.2 CLUTCH/BRAKE UNIT\n"
            "The press uses a pneumatically actuated clutch and brake unit. Air supply "
            "must be 6-8 bar, dry, and filtered. The clutch engages when the solenoid "
            "valve opens, releasing the spring-applied brake. Brake wear is indicated "
            "by increased stopping time. Measure the stopping angle annually — the "
            "crankshaft should stop within 30° of rotation from the clutch release point.\n\n"
            "1.3 FLYWHEEL SPECIFICATIONS\n"
            "Flywheel diameter: 1.8 m\n"
            "Flywheel speed: 180 RPM at 60 Hz\n"
            "Main motor: 55 kW, 480V 3-phase, 1200 RPM base speed\n"
            "VFD: Allen-Bradley PowerFlex 525, 75 kW\n"
            "Belt drive: 8V-2650, 6 belts",
            "7. TROUBLESHOOTING\n\n"
            "7.1 E101 — Drive Chain Binding\n\n"
            "CRITICAL: E101 on the Press-2001 means DRIVE CHAIN BINDING. It does NOT "
            "mean winding overtemperature (RoboInject-300) or low hydraulic pressure "
            "(Press-2000). Always verify the machine model before diagnosing.\n\n"
            "Meaning: The main drive chain tension is excessive, or the chain is catching "
            "on the chain guard. The controller detects increased torque demand on the "
            "flywheel motor via the VFD current monitoring circuit.\n\n"
            "Probable causes:\n"
            "1. Drive chain tension too high (overtightened) — the chain should have "
            "15-20 mm of vertical deflection at the center of the longest span when "
            "pressed with 5 kg force.\n"
            "2. Chain sprocket misalignment — the motor sprocket and flywheel sprocket "
            "must be aligned within ±1 mm.\n"
            "3. Worn chain links causing the chain to skip under load — inspect for "
            "stiff links, stretched pins, or uneven wear patterns.\n"
            "4. Foreign object caught in the chain guard — check for tools, debris, "
            "or rags that may have fallen into the chain enclosure.\n"
            "5. Flywheel bearing seizure — indicated by excessive heat or noise near "
            "the flywheel bearing housings.\n\n"
            "Corrective action:\n"
            "Step 1. Remove the chain guard (12 × M10 bolts). Inspect the chain visually "
            "for damage, stiff links, or foreign objects.\n"
            "Step 2. Measure chain tension at the center of the longest span. Using a "
            "spring scale, apply 5 kg of force to the chain. The deflection should be "
            "15-20 mm. Adjust by loosening the motor mounting plate bolts and moving "
            "the plate on the slide rails.\n"
            "Step 3. Check sprocket alignment using a straightedge placed across both "
            "sprockets. Misalignment greater than 2 mm causes accelerated chain and "
            "sprocket wear. Shim the motor mounting plate as needed.\n"
            "Step 4. Lubricate the chain with ISO-VG320 gear oil applied evenly across "
            "the full chain length. Run the motor without load for 5 minutes.\n"
            "Step 5. If binding persists, measure chain pitch. If the pitch has increased "
            "by more than 2% from the original specification, replace the chain set "
            "(P/N CH-2001-KIT includes chain and both sprockets).\n\n"
            "Source: Section 7, page 311.\n\n"
            "7.2 E204 — Flywheel Overspeed\n"
            "Meaning: The flywheel speed has exceeded 110% of rated maximum (198 RPM). "
            "The VFD has applied the dynamic brake resistor to slow the flywheel.\n\n"
            "Probable cause: VFD parameters misconfigured or feedback encoder fault. "
            "Check VFD parameter P-04 (Maximum Frequency) — should be 60 Hz for 180 RPM.",
            "7.3 E312 — Clutch Air Pressure Low\n\n"
            "Meaning: The air supply to the clutch solenoid valve has dropped below 5 bar. "
            "The press controller will not allow a cycle to start while the pressure is low.\n\n"
            "Corrective action:\n"
            "Step 1. Check the main air supply pressure at the regulator adjacent to the "
            "press. The regulator should be set to 6-8 bar.\n"
            "Step 2. Inspect the air line filter/water separator. Drain any accumulated "
            "water by opening the petcock at the bottom of the bowl.\n"
            "Step 3. Test the solenoid valve by applying 24V DC directly to the valve "
            "coil terminals. If the valve clicks but no air flows, the valve spool may "
            "be stuck. Remove and clean the spool. If the valve does not click, replace "
            "the coil (P/N V-SOL-2001).\n\n"
            "8. PERIODIC MAINTENANCE\n\n"
            "Daily: visually check chain tension, listen for abnormal gear noise, verify "
            "air pressure on the regulator gauge, check that the flywheel reaches full "
            "speed within 30 seconds of start.\n"
            "Weekly: lubricate the slide guide rails via grease fittings, drain the air "
            "line filter, visually inspect the clutch brake pads for wear.\n"
            "Monthly: check gearbox oil level, inspect flywheel bearing temperature "
            "by touch (should be cool to the touch after 30 minutes of operation), "
            "check belt tension and alignment.\n"
            "Annually: replace gearbox oil (ISO-VG220), replace clutch brake pads, "
            "perform a full electrical inspection of the VFD and motor windings, "
            "measure and record chain pitch for wear tracking.",
        ],
    )


def iso9001() -> None:
    build_pdf(
        "ISO-9001-Safety.pdf",
        "ISO 9001 Factory Safety & Lockout Guide",
        [
            "1. LOCKOUT / TAGOUT (LOTO) PROCEDURE\n\n"
            "Before any service work, the authorized technician must follow the "
            "company-mandated lockout/tagout procedure as required by OSHA 29 CFR "
            "1910.147 and ISO 9001 section 7.1.3. Failure to comply may result in "
            "severe injury or death.\n\n"
            "Step 1. NOTIFY: Inform all affected operators that the machine is being "
            "taken out of service for maintenance. Post the maintenance notice on the "
            "HMI screen.\n"
            "Step 2. IDENTIFY ENERGY SOURCES: Identify all energy sources for the "
            "specific machine being serviced:\n"
            "  - Electrical: main disconnect switch, control transformer, DC bus capacitors\n"
            "  - Pneumatic: compressed air supply line, accumulator tanks\n"
            "  - Hydraulic: main pump, accumulators, pressurized lines\n"
            "  - Mechanical: flywheel kinetic energy, spring-loaded mechanisms, "
            "counterbalance cylinders, suspended tooling\n"
            "Step 3. SHUTDOWN: Shut down the machine using the normal stop procedure. "
            "Allow the machine to come to a complete stop. For flywheel machines, this "
            "may take up to 2 minutes.\n"
            "Step 4. ISOLATE: Disconnect or isolate each energy source. Lock the main "
            "electrical disconnect switch in the OFF position using a personal padlock. "
            "Each technician working on the machine must apply their own lock.\n"
            "Step 5. DISSIPATE STORED ENERGY: Bleed hydraulic pressure by opening the "
            "pressure bleed valve. Discharge DC bus capacitors by shorting across the "
            "bus bars with a grounded discharge rod (rated for 1000V DC). Lower all "
            "suspended tooling or blocks. Release spring tension.\n"
            "Step 6. VERIFY ZERO ENERGY: Attempt to start the machine using the normal "
            "start button. The machine must not start. Verify that all motion has "
            "stopped and all pressure gauges read zero.\n"
            "Step 7. TAG: Apply a tag identifying the technician, the date, the "
            "expected completion time, and a description of the work being performed.\n\n"
            "WARNING: Never attempt to service a machine without completing all seven "
            "steps. Always verify zero energy state before touching any component.",
            "2. CROSS-MACHINE ERROR CODE REFERENCE\n\n"
            "This facility operates multiple machine types. The same error code may "
            "have DIFFERENT meanings on different machines. Always confirm the machine "
            "model before diagnosing any fault.\n\n"
            "E101 — CRITICAL: Different on every machine:\n"
            "  - RoboInject-300: Winding overtemperature (see RoboInject manual §4.2, p.214)\n"
            "  - Press-2000: Low hydraulic pressure (see Press-2000 manual §3.1, p.92)\n"
            "  - Press-2001: Drive chain binding (see Press-2001 manual §7.1, p.311)\n\n"
            "E204 — Also varies by machine:\n"
            "  - RoboInject-300: Servo stall detected (§8.3, p.312)\n"
            "  - Press-2000: High pressure exceeded (§5.2, p.138)\n"
            "  - Press-2001: Flywheel overspeed (§7.2, p.315)\n\n"
            "E302 — Varies:\n"
            "  - RoboInject-300: Zone 1 heater overcurrent (§9.1, p.378)\n\n"
            "Common codes (same meaning across all machines):\n"
            "  - E011: Safety loop open — one or more safety switches are not closed\n"
            "  - E099: Emergency stop activated — one or more E-stop buttons are pressed\n"
            "  - A107: Low lubrication oil level — central lubrication system needs refill\n\n"
            "IMPORTANT: If you are unsure which machine the error code refers to, "
            "identify the machine by its serial number prefix before proceeding:\n"
            "  - SM-: RoboInject-300 (injection molding)\n"
            "  - HY- or HP-: Press-2000 (hydraulic press)\n"
            "  - MP-: Press-2001 (mechanical press)",
            "3. GENERAL SAFETY RULES\n\n"
            "3.1 PERSONAL PROTECTIVE EQUIPMENT (PPE)\n"
            "All personnel in the production area must wear:\n"
            "- Hearing protection: earplugs or earmuffs rated ≥25 dB NRR\n"
            "- Safety glasses with side shields (ANSI Z87.1 compliant)\n"
            "- Steel-toed boots (ASTM F2413)\n"
            "- Close-fitting clothing (no loose sleeves, ties, or jewelry)\n"
            "- Gloves are prohibited around rotating machinery\n\n"
            "3.2 HOUSEKEEPING\n"
            "Keep the area around each machine clear of debris, oil spills, and unused "
            "tools. Any hydraulic or oil spill exceeding 0.5 L must be reported to the "
            "shift supervisor and cleaned using the spill kit located at each bay entrance. "
            "Use absorbent pads for oil and designate a waste disposal container.\n\n"
            "3.3 EMERGENCY PROCEDURES\n"
            "In the event of an injury:\n"
            "1. Press the nearest E-stop immediately.\n"
            "2. Call for assistance using the emergency phone (ext. 111) or the nearest "
            "emergency pull station.\n"
            "3. Provide first aid if trained and safe to do so.\n"
            "4. Do not attempt to move a person with suspected spinal injury.\n\n"
            "First-aid kits are located at each bay entrance. Fire extinguishers "
            "(Type ABC, 10 lb) are mounted at 20-meter intervals along the building "
            "columns. Automated external defibrillators (AEDs) are located at the "
            "main break room and the shipping/receiving office.\n\n"
            "3.4 REPORTING NEAR MISSES\n"
            "Any near-miss incident (e.g., a tool dropped inside a machine guard, a "
            "hydraulic line that burst while the machine was idle, a safety switch "
            "that failed to actuate during testing) must be reported to the safety "
            "department within 24 hours using form SAF-101. Near-miss reporting is "
            "a key component of ISO 9001 continuous improvement and is not disciplinary.",
        ],
    )


def powerflex() -> None:
    """Generate a realistic PowerFlex 525 drive manual with parameter tables."""
    build_pdf(
        "PowerFlex-525-Manual.pdf",
        "PowerFlex 525 Adjustable Frequency AC Drive — User Manual",
        [
            # Page 1
            "POWERFLEX 525 AC DRIVE — USER MANUAL\n"
            "Firmware Version 11.02\n"
            "Catalog Numbers: 25B-D1P4N104 through 25B-D480N104\n\n"
            "1. INTRODUCTION\n\n"
            "The PowerFlex 525 is a compact, multi-drive AC variable frequency drive "
            "designed for applications from 0.4 kW to 75 kW. It features built-in "
            "EtherNet/IP, dual-port Ethernet, and a removable HIM (Human Interface "
            "Module). This manual covers installation, configuration, parameter "
            "programming, troubleshooting, and maintenance.\n\n"
            "1.1 SAFETY\n"
            "WARNING: The drive contains hazardous voltages. The DC bus capacitors "
            "retain dangerous voltage for up to 5 minutes after power is removed. "
            "Always verify that the DC bus voltage is below 50V DC before touching "
            "any internal components.\n\n"
            "1.2 PARAMETER GROUP OVERVIEW\n"
            "Parameters are organized into groups identified by a letter prefix:\n"
            "  b — Basic Display: read-only status and monitoring parameters\n"
            "  A — Advanced Program: configuration and tuning parameters\n"
            "  C — Communications: network and serial port settings\n"
            "  d — Data: diagnostic and data logging parameters\n"
            "  F — Fault and Diagnostic: fault history and diagnostic data\n"
            "  G — Blower/Fan: cooling fan control parameters\n"
            "  P — Program: basic motor and drive program parameters\n"
            "  t — Timer/Counter: application timer and counter parameters\n\n"
            "1.3 BASIC DISPLAY PARAMETERS (b GROUP)\n"
            "The b group parameters are read-only and display real-time operating data:\n"
            "b001 Output Freq — Current output frequency to the motor in Hz.\n"
            "b002 Commanded Freq — The frequency command value in Hz.\n"
            "b003 Output Current — Motor output current in Amps.\n"
            "b004 Output Voltage — Motor output voltage in Volts.\n"
            "b005 DC Bus Voltage — DC bus voltage in Volts (nominal 650V DC for 480V input).\n"
            "b006 Drive Status — Current drive state (Ready, Run, Fault, etc.).\n"
            "b007 Fault 1 Code — Most recent fault code.\n"
            "b008 Fault 2 Code — Second most recent fault code.\n"
            "b009 Fault 3 Code — Third most recent fault code.\n"
            "b010 Process Fract — Process variable fractional display.\n"
            "b011 Process Units — Process variable in engineering units.\n"
            "b012 Control Source — Active control source (HIM, Network, Terminal, etc.).\n"
            "b013 Control In Status — Digital input status display.\n"
            "b014 Dig In Status — Terminal block digital input status.\n"
            "b015 Dig Out Status — Terminal block digital output status.\n"
            "b016 Speed Feedback — Actual motor speed feedback in RPM.\n"
            "b017 Elapsed Run Time — Total run time in hours.\n"
            "b018 Power Saved — Estimated power savings in MWh.\n"
            "b019 Accum MWh — Total accumulated energy in MWh.\n"
            "b020 Accum Cost Sav — Estimated energy cost savings.",
            # Page 2
            "2. INSTALLATION\n\n"
            "2.1 ENVIRONMENTAL REQUIREMENTS\n"
            "Ambient temperature: 0°C to 50°C (derate to 90% above 40°C)\n"
            "Humidity: 5% to 95% non-condensing\n"
            "Altitude: up to 1000 m without derating, 1% per 100 m above 1000 m\n"
            "Enclosure: IP20 (NEMA 1) standard, IP54 option available\n\n"
            "2.2 POWER WIRING\n"
            "Use copper wire rated for 75°C minimum. Tighten all power terminals to "
            "the torque specified in Table 2.1. Route power wiring and control wiring "
            "in separate conduits, separated by at least 150 mm. If crossing is "
            "unavoidable, cross at a 90° angle.\n\n"
            "2.3 CONTROL WIRING\n"
            "Control terminals accept 0.5 mm² to 2.5 mm² wire. Use shielded twisted "
            "pair cable for analog and communication signals. Connect the shield at "
            "the drive end only. Ground the shield via the shield clamp inside the "
            "drive enclosure.\n\n"
            "2.4 FUSE AND CIRCUIT BREAKER RATINGS\n"
            "Catalog 25B-D1P4N104 (0.4 kW): 6A class CC fuse\n"
            "Catalog 25B-D6P0N104 (3.0 kW): 20A class CC fuse\n"
            "Catalog 25B-D019N104 (9.0 kW): 50A class J fuse\n"
            "Catalog 25B-D480N104 (75 kW): 200A class J fuse\n\n"
            "3. PROGRAMMING\n\n"
            "3.1 ADVANCED PROGRAM GROUP (A GROUP)\n"
            "A410 Preset Freq 0 — First preset frequency reference.\n"
            "A411 Preset Freq 1 — Second preset frequency reference.\n"
            "A444 Accel Time 3 — Third acceleration ramp time in seconds.\n"
            "A445 Decel Time 3 — Third deceleration ramp time in seconds.\n"
            "A479 PID 2 Invert Err — Invert the PID 2 error signal.\n"
            "A481 Process Disp Lo — Low value for process display scaling.\n"
            "A519 PM HIFI NS Cur(1) — Permanent magnet motor nominal current.\n"
            "A520 PM Bus Reg Kd(1) — PM motor bus regulator derivative gain.\n"
            "A554 Drv Ambient Sel — Drive ambient temperature sensor selection.\n"
            "A555 Reset Meters — Reset accumulated energy and run time meters.\n\n"
            "3.2 COMMUNICATIONS GROUP (C GROUP)\n"
            "C143 Comm Flt Actn — Action on communication fault (0=Stop, 1=Hold, 2=Alarm).\n"
            "C156 EN Data In 4 — EtherNet/IP data input word 4.\n"
            "C157 Opt Data Out 3 — Option module data output word 3.\n"
            "C158 EN Rcv Data 1 — Ethernet received data word 1.",
            # Page 3
            "4. FAULT AND DIAGNOSTIC INFORMATION\n\n"
            "4.1 FAULT CODE DESCRIPTIONS\n\n"
            "F004 — UnderVoltage (DC bus voltage below 400V DC)\n"
            "Meaning: The DC bus voltage has fallen below the undervoltage threshold "
            "of 400V DC. This is typically caused by a loss of input AC power, a "
            "blown input fuse, or a severely sagging AC line voltage.\n\n"
            "F005 — OverVoltage (DC bus voltage above 815V DC)\n"
            "Meaning: The DC bus voltage has exceeded the overvoltage threshold of "
            "815V DC. This is typically caused by excessive regenerative energy from "
            "the motor during deceleration, or a transient overvoltage on the AC input.\n\n"
            "F006 — Motor Stalled\n"
            "Meaning: The motor rotor has stalled or is rotating at less than 25% of "
            "the commanded speed. The stall condition must persist for the stall time "
            "set in parameter P-36 (default 3 seconds) before the fault is triggered.\n\n"
            "F008 — Motor Overload\n"
            "Meaning: The motor current has exceeded the overload current rating set "
            "in parameter P-35 (default 150% of motor FLA) for longer than the "
            "allowable time. The drive uses an I²t thermal model to calculate motor "
            "heating.\n\n"
            "F009 — Drive Overload\n"
            "Meaning: The drive output current has exceeded 110% of the drive's rated "
            "output current. The drive's internal I²t overload protection has tripped.\n\n"
            "F012 — Ground Fault\n"
            "Meaning: A ground fault has been detected on the drive output. The drive "
            "senses current imbalance between the three output phases exceeding 50% "
            "of the rated current. Check motor wiring insulation.\n\n"
            "F013 — Hardware OverCurrent\n"
            "Meaning: Instantaneous peak current exceeded 200% of the drive rating. "
            "This is a hardware-level fault, not a software overload. Check for a "
            "shorted motor or damaged output IGBT.\n\n"
            "F071 — PI Feedback Loss\n"
            "Meaning: The PID feedback signal has fallen below the loss threshold set "
            "in parameter A-469 for longer than the loss time set in A-470.\n\n"
            "F080 — Safe Torque Off\n"
            "Meaning: The Safe Torque Off (STO) circuit has been activated. "
            "Check the STO input terminals and the safety system.",
            # Page 4
            "4.2 FAULT HISTORY PARAMETERS\n"
            "The drive records the last 10 faults with time and operating data:\n"
            "F604 Fault 4 Code — Fourth fault code.\n"
            "F605 Fault 5 Code — Fifth fault code.\n"
            "F606 Fault 6 Code — Sixth fault code.\n"
            "F607 Fault 7 Code — Seventh fault code.\n"
            "F608 Fault 8 Code — Eighth fault code.\n"
            "F609 Fault 9 Code — Ninth fault code.\n"
            "F610 Fault 10 Code — Tenth fault code.\n\n"
            "Each fault record also stores:\n"
            "F627 Fault 1 Time-min — Fault 1 occurrence time in minutes.\n"
            "F628 Fault 2 Time-min — Fault 2 occurrence time in minutes.\n"
            "F629 Fault 3 Time-min — Fault 3 occurrence time in minutes.\n\n"
            "F651 Fault 1 BusVolts — DC bus voltage at the time of Fault 1.\n"
            "F652 Fault 2 BusVolts — DC bus voltage at the time of Fault 2.\n"
            "F653 Fault 3 BusVolts — DC bus voltage at the time of Fault 3.\n\n"
            "5. TROUBLESHOOTING\n\n"
            "5.1 DRIVE DOES NOT START\n"
            "Check: AC power present (LED D1 green), control power present, enable "
            "input closed, no active faults, speed reference above 0 Hz.\n\n"
            "5.2 MOTOR RUNS ERRATICALLY\n"
            "Check: motor data programmed correctly (P-01 through P-06), autotune "
            "completed (P-40), input voltage stable, ground faults absent.\n\n"
            "5.3 DRIVE OVERHEATING\n"
            "Check: cooling fan operation (D1 on the control board), ambient "
            "temperature, air filter, drive loading not exceeding rated current.\n\n"
            "6. MAINTENANCE\n\n"
            "6.1 COOLING FAN REPLACEMENT\n"
            "The internal cooling fan (P/N PF-525-FAN) should be replaced every "
            "40,000 hours of operation. The fan is located behind the front cover, "
            "secured by two M4 screws. Disconnect the fan connector from the control "
            "board (J14) before removing.\n\n"
            "6.2 CAPACITOR FORMATION\n"
            "If the drive has been stored for more than 12 months without power, "
            "the DC bus capacitors must be reformed before applying full power. "
            "Apply 50% of the rated voltage for 30 minutes, then 75% for 30 minutes, "
            "before applying full power.",
        ],
    )


def main() -> None:
    print(f"Generating dense synthetic manuals in {OUT}\n")
    roboinject()
    press2000()
    press2001()
    iso9001()
    powerflex()
    print("\nDone.")


if __name__ == "__main__":
    main()